[package]
name = "tess-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.8"
opencv = "0.79.0"
tesseract = "0.13.0"
